version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
      - "443:443"
    volumes:
      - /opt/ssl:/app/ssl:ro
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - /opt/ssh-keys:/app/ssh-keys:ro
    environment:
      - NODE_ENV=production
      - PORT=8000
      - LOG_LEVEL=info
      - LOG_PATH=/app/logs
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
    driver: local
  logs:
    driver: local